import {
  BookText,
  CodeSquare,
  HomeIcon,
  UserRound,
  Linkedin,
  Twitter,
  Rss,
  Twitch,
  Youtube,
  Crop,
  Pencil,
  Computer,
  Book,
  Rocket,
  Speech,
  GitBranch,
  Gitlab,
  Github,
  DatabaseIcon,
  DockIcon,
  Server,
  Layout,
  Layers,
  Cloud,
  Workflow,
  Users,
} from "lucide-react";

export const socialNetworks = [
  {
    id: 2,
    logo: <Linkedin size={30} strokeWidth={1} />,
    src: "https://www.linkedin.com/in/adrian-castro-241857149/",
  },
  {
    id: 3,
    logo: <Github size={30} strokeWidth={1} />,
    src: "https://github.com/Dev-Drian",
  },
];

export const itemsNavbar = [
  {
    id: 1,
    title: "Home",
    icon: <HomeIcon size={25} color="#fff" strokeWidth={1} />,
    link: "/",
  },
  {
    id: 2,
    title: "User",
    icon: <UserRound size={25} color="#fff" strokeWidth={1} />,
    link: "/about-me",
  },
  {
    id: 3,
    title: "Book",
    icon: <BookText size={25} color="#fff" strokeWidth={1} />,
    link: "/services",
  },
  {
    id: 4,
    title: "Target",
    icon: <CodeSquare size={25} color="#fff" strokeWidth={1} />,
    link: "/portafolio",
  },
];

export const dataAboutPage = [
  {
    id: 1,
    title: "Ingeniería de Sistemas",
    subtitle: "Tecnológico Comfenalco · Cartagena, Colombia",
    description:
      "Formación profesional en desarrollo de software, bases de datos, arquitectura de sistemas y metodologías ágiles. Skills: Java, Spring Boot, Python, .NET, Vue, React, React Native, Next.js, TypeScript, Node.js, NestJS, Laravel, MySQL, SQL Server, GraphQL, Docker, CI/CD, Git.",
    date: "Ene 2021",
    endDate: "Dic 2025",
    color: "cyan",
    icon: "education",
    isEducation: true,
  },
  {
    id: 2,
    title: "Analista Desarrollador",
    subtitle: "Comfenalco · Cartagena, Colombia",
    description:
      "Participé en el desarrollo de aplicaciones académicas, priorizando rendimiento, escalabilidad y buenas prácticas de código. Implementé dashboards y optimicé consultas en base de datos para mejorar el control y la toma de decisiones institucionales.",
    date: "Ene 2022",
    endDate: "Mar 2025",
    color: "emerald",
    icon: "code",
  },
  {
    id: 3,
    title: "Líder de Desarrollo Full Stack",
    subtitle: "Limo Partner · Estados Unidos",
    description:
      "Lideré el diseño, desarrollo y evolución de un CRM a medida que centraliza la operación de la compañía, integrando APIs externas (mensajería y notificaciones en tiempo real) y automatizando procesos administrativos clave. Logré un 40% de mejora en el proceso productivo y un 30% en rendimiento de los servicios.",
    date: "Oct 2022",
    endDate: "Dic 2025",
    color: "purple",
    icon: "rocket",
  },
  {
    id: 4,
    title: "Desarrollador Full Stack",
    subtitle: "Cotecmar · Cartagena, Colombia",
    description:
      "Participé en el desarrollo de soluciones institucionales utilizando tecnologías modernas, asegurando rendimiento, escalabilidad y mantenimiento sostenible del código. Implementé dashboards de seguimiento y optimicé consultas complejas en base de datos para procesos administrativos.",
    date: "Jul 2025",
    endDate: "Actualidad",
    color: "blue",
    icon: "ship",
  },
  {
    id: 5,
    title: "Desarrollador Full Stack",
    subtitle: "Saroa SAS · Cartagena, Colombia",
    description:
      "Desarrollo soluciones enfocadas en la gestión de planes y control de alimentación para entidades públicas (Ministerio de Educación), asegurando organización, trazabilidad y correcta administración de la información. Contribuyo a la mejora continua del sistema mediante ajustes en arquitectura.",
    date: "Nov 2025",
    endDate: "Actualidad",
    color: "orange",
    icon: "food",
  },
];

export const dataCounter = [
  {
    id: 0,
    endCounter: 4,
    text: "Años de experiencia",
    lineRight: true,
    lineRightMobile: true,
    icon: "rocket",
  },
  {
    id: 1,
    endCounter: 25,
    text: "Clientes satisfechos",
    lineRight: true,
    lineRightMobile: false,
    icon: "star",
  },
  {
    id: 2,
    endCounter: 18,
    text: "Proyectos finalizados",
    lineRight: true,
    lineRightMobile: false,
    icon: "code",
  },
  {
    id: 3,
    endCounter: 500,
    text: "Commits realizados",
    lineRight: false,
    lineRightMobile: false,
    icon: "coin",
  },
];

export const serviceData = [
  {
    icon: <Server />,
    title: "Desarrollo Backend",
    description: "Diseño e implementación de APIs RESTful, microservicios y arquitecturas escalables con enfoque en seguridad y rendimiento.",
    tags: ["Laravel", "NestJS", ".NET", "Node.js", "Spring Boot"],
    color: "purple",
  },
  {
    icon: <Layout />,
    title: "Desarrollo Frontend",
    description: "Creación de interfaces modernas, responsivas y accesibles. Single Page Applications con frameworks de última generación.",
    tags: ["React", "Next.js", "Vue.js", "Angular"],
    color: "cyan",
  },
  {
    icon: <Layers />,
    title: "Soluciones Fullstack",
    description: "Desarrollo integral de aplicaciones web completas, desde la base de datos hasta la interfaz de usuario.",
    tags: ["Laravel + Vue", "React + Node", "Next.js + NestJS"],
    color: "emerald",
  },
  {
    icon: <Cloud />,
    title: "DevOps & Cloud",
    description: "Configuración de entornos en la nube, contenedores y pipelines de CI/CD para despliegues automatizados.",
    tags: ["Docker", "Azure", "GitHub Actions", "Linux"],
    color: "blue",
  },
  {
    icon: <Workflow />,
    title: "Automatización de Procesos",
    description: "Diseño de workflows con n8n para integrar sistemas, automatizar tareas repetitivas y optimizar operaciones.",
    tags: ["n8n", "Make", "Zapier", "APIs", "Webhooks"],
    color: "orange",
  },
  {
    icon: <Users />,
    title: "Gestión Ágil de Proyectos",
    description: "Experiencia en equipos Scrum, planificación de sprints, estimación y entrega continua de valor.",
    tags: ["Scrum", "Kanban", "Jira", "Git Flow"],
    color: "pink",
  },
];

export const dataPortfolio = [
  {
    id: 1,
    title: "CRM Limo Partner",
    image: "/quoterides.png",
    urlGithub: "#!",
    urlDemo: "https://portal.crm.limo",
    description: "CRM completo para transporte ejecutivo con integración de APIs externas, sistema de reservas, cotizaciones automatizadas, notificaciones en tiempo real y optimización SEO.",
    tags: ["Laravel", "Vue.js", "APIs", "SEO"],
    color: "purple",
  },
  {
    id: 2,
    title: "SIGE - ESAP",
    image: "/esap.png",
    urlGithub: "#!",
    urlDemo: "https://www.esap.edu.co/academia/estudiantes/",
    description: "Sistema de Información y Gestión para la Escuela Superior de Administración Pública. Gestión integral de personas, roles y procesos académicos.",
    tags: ["React", "Next.js", "SQL Server"],
    color: "blue",
  },
  {
    id: 3,
    title: "Quote Rides",
    image: "/quoterides.png",
    urlGithub: "#!",
    urlDemo: "https://crm.quoterides.com",
    description: "Landing page y sistema de cotizaciones para servicio de transporte premium con integración WordPress y optimización de conversión.",
    tags: ["JavaScript", "WordPress", "PHP"],
    color: "cyan",
  },
  {
    id: 4,
    title: "SIGEPAE - MinEducación",
    image: "/sigepae.png",
    urlGithub: "#!",
    urlDemo: "https://sipae.gov.co",
    description: "Ecosistema de información para el programa 'Alimentos para Aprender' del Ministerio de Educación Nacional. Control y trazabilidad alimentaria.",
    tags: ["Angular", ".NET", "SQL Server"],
    color: "emerald",
  },
  {
    id: 5,
    title: "TOP - Cotecmar",
    image: "/top.png",
    urlGithub: "#!",
    urlDemo: "https://top.cotecmar.com/dashboard",
    description: "Portal de empleados y Dashboard de ofertas para Cotecmar. Gestión de actividades, balance general y seguimiento de proyectos navales.",
    tags: ["Vue.js", "Laravel", "SQL Server"],
    color: "indigo",
  },
  {
    id: 6,
    title: "Nova",
    image: "/nova.jpeg",
    urlGithub: "#!",
    urlDemo: "https://tecnologicocomfenalco.edu.co",
    description: "Aplicación de gestión empresarial con módulos de inventario, facturación y reportes dinámicos para PYMES.",
    tags: ["Laravel", "Livewire", "MySQL"],
    color: "pink",
  },
  {
    id: 7,
    title: "Tecnoi Prog",
    image: "/ikarus.jpeg",
    urlGithub: "#!",
    urlDemo: "https://tecnopro.tecnologicocomfenalco.edu.co/login",
    description: "Sistema de monitoreo y análisis de datos en tiempo real para optimización de procesos empresariales.",
    tags: ["Laravel", "Vue.js", "PostgreSQL"],
    color: "orange",
  },
  {
    id: 10,
    title: "239 Web",
    image: "/quoterides.png",
    urlGithub: "#!",
    urlDemo: "https://portal.239web.com",
    description: "CRM de Marketing Digital con estrategias SEO, Social Media, PPC y Analytics. Sitios web personalizados, optimizados para buscadores y conversión.",
    tags: ["Laravel", "Vue.js", "SEO", "Marketing"],
    color: "cyan",
  },
  {
    id: 8,
    title: "Elguedo & Asociados",
    image: "/abogados elguedo y aosicados .png",
    urlGithub: "#!",
    urlDemo: "https://elguedoyasociados.com",
    description: "Landing page profesional para bufete de Abogados Laboralistas en Cartagena. Diseño elegante con integración de WhatsApp y formulario de contacto.",
    tags: ["Next.js", "Tailwind CSS", "SEO"],
    color: "amber",
  },
  {
    id: 11,
    title: "Livewire CountUp",
    image: "/quoterides.png",
    urlGithub: "https://github.com/Dev-Drian/livewire-countUp",
    urlDemo: "#!",
    description: "Paquete open source para Laravel que integra contadores animados usando Livewire y Alpine.js. Incremento animado, personalización extensa y compatible con Tailwind CSS.",
    tags: ["Laravel", "Livewire", "Alpine.js", "Open Source"],
    color: "emerald",
  },
];

